/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}"
  ],
  theme: {
    extend: {
      colors: {
        background: '#070b14',
        surface: '#0f1629',
        'surface-container': '#161f35',
        'surface-container-low': '#0f1629',
        'surface-container-high': '#161f35',
        'surface-container-highest': '#1e2a42',
        'surface-variant': '#161f35',
        'surface-bright': '#1e2a42',
        primary: '#6c63ff',
        'primary-container': '#6c63ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#ffffff',
        secondary: '#00d4b1',
        'secondary-container': '#00d4b1',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#ffffff',
        tertiary: '#f5a623',
        'tertiary-container': '#f5a623',
        'on-tertiary': '#ffffff',
        error: '#ff6b8a',
        'error-container': '#ff6b8a',
        'on-error': '#ffffff',
        'on-surface': '#eef2ff',
        'on-surface-variant': '#8892b0',
        outline: '#4a5568',
        'outline-variant': '#1e2a42',
        'inverse-primary': '#6c63ff',
        // Add explicit new palette variables
        'app-bg': '#070b14',
        'surface-1': '#0f1629',
        'surface-2': '#161f35',
        'surface-3': '#1e2a42',
        'accent-purple': '#6c63ff',
        'accent-teal': '#00d4b1',
        'accent-amber': '#f5a623',
        'accent-rose': '#ff6b8a',
        'text-primary': '#eef2ff',
        'text-secondary': '#8892b0',
        'text-muted': '#4a5568',
        'border-subtle': 'rgba(255,255,255,0.06)',
        'border-medium': 'rgba(255,255,255,0.12)',
      },
      fontFamily: {
        plus: ['PlusJakartaSans_400Regular'],
        'plus-medium': ['PlusJakartaSans_500Medium'],
        'plus-semibold': ['PlusJakartaSans_600SemiBold'],
        'plus-bold': ['PlusJakartaSans_700Bold'],
        'plus-extrabold': ['PlusJakartaSans_800ExtraBold'],
        space: ['SpaceGrotesk_500Medium'],
        'space-semibold': ['SpaceGrotesk_600SemiBold'],
        'space-bold': ['SpaceGrotesk_700Bold'],
      },
      spacing: {
        'container-padding': '20px',
        'stack-loose': '24px',
        'card-gap': '16px',
        gutter: '12px',
        'stack-tight': '4px',
      }
    },
  },
  plugins: [],
}
